name: 'Github Testing'
description: 'Testing the ts running in github actions'
inputs:
  name:
    description: 'Name to greet'
    required: false
    default: 'Vedavyas'
  ghToken:
    description: 'GitHub access token'
    required: false
outputs:
  token:
    description: 'affdf'
    value: ${{ steps.sample.outputs.token }}

runs:
  using: 'node16'
  steps: sample
  main: 'dist/gettoken.js'
  